# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20180526_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('u_email', models.CharField(max_length=32, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons')),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
